{{- $cupsd := .Values.config.cupsd | required ".Values.config.cupsd must be defined. Set the value from respective files specified via the helm command line with --set-file=config.cupsd=<somefolder>/cupsd.conf" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cups.fullname" . }}-conf
data:
  cupsd.conf: |
    {{- $cupsd | nindent 4 }}